server:
  port: ${port:5001}
  tomcat:
    uri-encoding: UTF-8
#    max-swallow-size: -1    # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

spring:
  application:
    name: file-service
  profiles:
    active: dev
  banner:
    location: classpath:banner/qsmx.txt
  servlet:
    multipart:
      max-file-size: 500KB # 单个文件最大500KB
      max-request-size: 500KB # 一次请求最大500KB