spring:
  cloud:
    nacos:
      discovery:
        server-addr:
        username:
        password:
        namespace:
    gateway:
      discovery:
        locator:
          enabled: true #动态路由，从注册中心更具微服务的名字获取目标节点的地址
      routes: #路由规则
        - id: userRouter #每一项路由都有一个唯一的id
          uri: lb://user-service #lb负载均衡，会动态寻址
          predicates: #匹配断言，符合条件的放行，可以模糊也可以具体匹配
            - Path=/u/**
        - id: companyRouter #每一项路由都有一个唯一的id
          uri: lb://company-service #lb负载均衡，会动态寻址
          predicates: #匹配断言，符合条件的放行，可以模糊也可以具体匹配
            - Path=/c/**
        - id: authRouter #每一项路由都有一个唯一的id
          uri: lb://auth-service #lb负载均衡，会动态寻址
          predicates: #匹配断言，符合条件的放行，可以模糊也可以具体匹配
            - Path=/a/**,/passport/**,/saas/**,/admin/**
  # 跨域配置
  #      globalcors:
  #        cors-configurations:
  #          '[/**]':
  #            allowed-headers: "*"
  #            allowed-methods: "*"
  #            allowed-origin-patterns: "*"
  #            allowed-origins: true
  redis:
    host:
    port:
    database: 0
    password: